name: Build Hero SVG

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Generate Hero
        run: npm run build

      - name: Commit Hero
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Update hero.svg"